include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # 함수 및 메서드에 반환 타입을 항상 선언하도록 합니다.
    always_declare_return_types: true

    # 변수를 명시적으로 null로 초기화하지 않도록 합니다.
    avoid_init_to_null: true

    # 클래스와 타입의 이름을 카멜 케이스(camelCase)로 작성하도록 합니다.
    camel_case_types: true

    # 상수 이름을 SCREAMING_CAPS(대문자와 언더스코어)로 작성하도록 합니다.
    constant_identifier_names: true

    # 제어문(if, else, for, while 등)에서 중괄호를 사용하여 코드 블록을 명확하게 구분하도록 합니다.
    curly_braces_in_flow_control_structures: true

    # 파일 이름을 스네이크 케이스(snake_case)로 작성하도록 합니다.
    file_names: true

    # 코드의 각 줄이 80자를 넘지 않도록 합니다.
    lines_longer_than_80_chars: true

    # 상수가 아닌 식별자(변수, 함수, 메서드 등)의 이름을 카멜 케이스로 작성하도록 합니다.
    non_constant_identifier_names: true

    # 가능한 경우 const 생성자를 사용하도록 합니다.
    prefer_const_constructors: true

    # 로컬 변수를 변경할 필요가 없는 경우 final로 선언하도록 합니다.
    prefer_final_locals: true

    # `print` 문을 사용하는 것을 피하도록 권장합니다.
    avoid_print: true

    # 문자열을 표현할 때 작은따옴표('')를 사용하는 것을 선호하도록 권장합니다.
    prefer_single_quotes: true
